# Generated by shipshape; do not edit by hand (template-version: 2)
class Shipshape < Formula
  desc "Release & readiness coordinator"
  homepage "https://github.com/jarimustonen/ossctl"
  version "0.11.0"
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jarimustonen/ossctl/releases/download/v0.11.0/shipshape-aarch64-apple-darwin.tar.xz"
    sha256 "15c35f00196da6da1d5d852b99dd5de51d8f1895aa97207690814b581273c988"
  end
  if OS.linux? && Hardware::CPU.arm?
    url "https://github.com/jarimustonen/ossctl/releases/download/v0.11.0/shipshape-aarch64-unknown-linux-musl.tar.xz"
    sha256 "b510af6cefcdf59b0d18dc0176620e19f40d81e0a5fb5a259544eeaeb39057fa"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jarimustonen/ossctl/releases/download/v0.11.0/shipshape-x86_64-unknown-linux-musl.tar.xz"
    sha256 "83313adf0e1bc91cffb78fea7146f3ecc8280a58b57180c5a0d1cbb3989d9d86"
  end
  license "MIT"
  def install
    bin.install "shipshape"
  end

  test do
    system bin/"shipshape", "version"
  end
end
